### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by SamVerschueren** [extroncore/g14EvaWebapp#1]
`node_modules` and `bower_components` do not belong on github as they can be easily installed by team members with `npm install` and `bower install`.

So best practice is to add a `.gitignore` file.

```
node_modules
bower_components
.sass-cache
```

This reduces the amount of data that team members have to download when pulling the repository.

// @rappitbe

**Comment by rappitbe** [comment]
Totally true! Glad to have you on board Sam. 

Next best practice: follow Sam on twitter.

**Comment by SamVerschueren** [comment]
@rappitbe I guess it's more interesting to follow [Sindre Sorhus](https://twitter.com/sindresorhus), [Addy Osmani](https://twitter.com/addyosmani) and many others ;).
